# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trading.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrading.proto\"\x1f\n\rSignalRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\" \n\x0eSignalResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t2?\n\x0eTradingService\x12-\n\nSendSignal\x12\x0e.SignalRequest\x1a\x0f.SignalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQUEST']._serialized_start=17
  _globals['_SIGNALREQUEST']._serialized_end=48
  _globals['_SIGNALRESPONSE']._serialized_start=50
  _globals['_SIGNALRESPONSE']._serialized_end=82
  _globals['_TRADINGSERVICE']._serialized_start=84
  _globals['_TRADINGSERVICE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
