name: CoreFlow Snapshot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Täglich um 2 Uhr UTC

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt || true  # ignoriert Fehler wenn requirements.txt fehlt

      - name: Run CoreFlow Healthcheck
        run: |
          source venv/bin/activate
          ./scripts/coreflow_main.py --healthcheck || echo "Healthcheck failed"
