name: Snapshot Creator

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Täglich um 2:00 UTC

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "ynutsgroup-bot"
          git config user.email "bot@ynuts.com"

      - name: Create timestamped tag
        run: |
          TAG="snapshot-$(date +'%Y%m%d-%H%M')"
          git tag "$TAG"
          git push origin "$TAG"
